version: "3.8"

services:
    caddy:
        image: caddy:alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            - web
            - max.hole.pictures
        volumes: 
            - /srv/caddy:/etc/caddy
            - /srv/html:/srv
            - /srv/caddy/data:/data
            - /srv/caddy/config:/config

networks:
    web:
        name: web
    max.hole.pictures:
        external: true
